### ISSUE TITLE
Code running error

### ISSUE THREAD

**Issue by DKay7** [shentianxiao/text-autoencoders#10]
Hi, thank you for such a great implementation. I found a little error:
```
Traceback (most recent call last):
  File "text-autoencoders/train.py", line 9, in <module>
    from model import DAE, VAE, AAE
  File "text-autoencoders/model.py", line 70
    def generate(self, z, max_len, alg):
                                       ^
IndentationError: unindent does not match any outer indentation level
```
It's easy to fix and I've already fix it locally. So, please, fix it in the next commit. Thank you!

**Comment by shentianxiao** [comment]
It's now been fixed. Thanks for pointing out.
